#! /usr/bin/env python
import subprocess

result = subprocess.run(["amixer", "-D", "pulse", "sset", "Master", "5%+"], stderr=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
volume = subprocess.run(["get-volume"], stderr=subprocess.PIPE, stdout=subprocess.PIPE, text=True).stdout
subprocess.run(["dunstify", "-h", "string:x-canonical-private-synchronous:audio", "Volume: " + volume, "-h", "int:value:" + volume])
