require("jas.options")
require("jas.plugins")
require("jas.treesitter")
require("jas.blankline")
require("jas.keymaps")
require("jas.lualine")
require("jas.cmp")
require("jas.comment")
require("jas.colorizer")
require("jas.nvim-tree")
require("jas.telescope")
require("jas.lsp.mason")
require("jas.lsp.lspsaga")
require("jas.lsp.lspconfig")
require("jas.lsp.null-ls")
vim.cmd("source /home/jas/.config/nvim/vim-theme/everforest.vim")
